# Generated by Django 5.1.6 on 2026-03-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('llm_model', models.CharField(default='', max_length=128)),
                ('stt_model', models.CharField(default='', max_length=128)),
                ('tts_model', models.CharField(default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
