# Generated by Django 5.1.6 on 2026-03-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_extend_lead_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleOAuthToken",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                (
                    "token_uri",
                    models.URLField(default="https://oauth2.googleapis.com/token"),
                ),
                ("client_id", models.CharField(max_length=256)),
                ("client_secret", models.CharField(max_length=256)),
                (
                    "scopes",
                    models.TextField(
                        default="https://www.googleapis.com/auth/spreadsheets"
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Google OAuth Token",
                "verbose_name_plural": "Google OAuth Tokens",
            },
        ),
    ]
