# Generated by Django 5.1.6 on 2026-03-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_googleoauthtoken'),
    ]

    operations = [
    ]
