# Generated by Django 5.1.6 on 2026-03-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_oauth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='update_type',
        ),
        migrations.AddField(
            model_name='lead',
            name='intent',
            field=models.CharField(blank=True, choices=[('sell', 'Sell'), ('update', 'Update'), ('unclear', 'Unclear/Other')], default='', max_length=32),
        ),
    ]
